// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class HomepageBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout covermenu;

  @NonNull
  public final Button helpcenter;

  @NonNull
  public final Button openmenu;

  @NonNull
  public final Button setuse;

  private HomepageBinding(@NonNull LinearLayout rootView, @NonNull LinearLayout covermenu,
      @NonNull Button helpcenter, @NonNull Button openmenu, @NonNull Button setuse) {
    this.rootView = rootView;
    this.covermenu = covermenu;
    this.helpcenter = helpcenter;
    this.openmenu = openmenu;
    this.setuse = setuse;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static HomepageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static HomepageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.homepage, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static HomepageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.covermenu;
      LinearLayout covermenu = ViewBindings.findChildViewById(rootView, id);
      if (covermenu == null) {
        break missingId;
      }

      id = R.id.helpcenter;
      Button helpcenter = ViewBindings.findChildViewById(rootView, id);
      if (helpcenter == null) {
        break missingId;
      }

      id = R.id.openmenu;
      Button openmenu = ViewBindings.findChildViewById(rootView, id);
      if (openmenu == null) {
        break missingId;
      }

      id = R.id.setuse;
      Button setuse = ViewBindings.findChildViewById(rootView, id);
      if (setuse == null) {
        break missingId;
      }

      return new HomepageBinding((LinearLayout) rootView, covermenu, helpcenter, openmenu, setuse);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
