// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class HomepageadminBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button airline;

  @NonNull
  public final Button attract;

  @NonNull
  public final LinearLayout covermenuad;

  @NonNull
  public final Button helpadmin;

  @NonNull
  public final Button hotel;

  @NonNull
  public final Button messages;

  @NonNull
  public final Button openmenuad;

  @NonNull
  public final Button out;

  @NonNull
  public final Button restaurant;

  @NonNull
  public final Button roles;

  @NonNull
  public final Button set;

  @NonNull
  public final Button transport;

  @NonNull
  public final Button users;

  private HomepageadminBinding(@NonNull LinearLayout rootView, @NonNull Button airline,
      @NonNull Button attract, @NonNull LinearLayout covermenuad, @NonNull Button helpadmin,
      @NonNull Button hotel, @NonNull Button messages, @NonNull Button openmenuad,
      @NonNull Button out, @NonNull Button restaurant, @NonNull Button roles, @NonNull Button set,
      @NonNull Button transport, @NonNull Button users) {
    this.rootView = rootView;
    this.airline = airline;
    this.attract = attract;
    this.covermenuad = covermenuad;
    this.helpadmin = helpadmin;
    this.hotel = hotel;
    this.messages = messages;
    this.openmenuad = openmenuad;
    this.out = out;
    this.restaurant = restaurant;
    this.roles = roles;
    this.set = set;
    this.transport = transport;
    this.users = users;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static HomepageadminBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static HomepageadminBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.homepageadmin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static HomepageadminBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.airline;
      Button airline = ViewBindings.findChildViewById(rootView, id);
      if (airline == null) {
        break missingId;
      }

      id = R.id.attract;
      Button attract = ViewBindings.findChildViewById(rootView, id);
      if (attract == null) {
        break missingId;
      }

      id = R.id.covermenuad;
      LinearLayout covermenuad = ViewBindings.findChildViewById(rootView, id);
      if (covermenuad == null) {
        break missingId;
      }

      id = R.id.helpadmin;
      Button helpadmin = ViewBindings.findChildViewById(rootView, id);
      if (helpadmin == null) {
        break missingId;
      }

      id = R.id.hotel;
      Button hotel = ViewBindings.findChildViewById(rootView, id);
      if (hotel == null) {
        break missingId;
      }

      id = R.id.messages;
      Button messages = ViewBindings.findChildViewById(rootView, id);
      if (messages == null) {
        break missingId;
      }

      id = R.id.openmenuad;
      Button openmenuad = ViewBindings.findChildViewById(rootView, id);
      if (openmenuad == null) {
        break missingId;
      }

      id = R.id.out;
      Button out = ViewBindings.findChildViewById(rootView, id);
      if (out == null) {
        break missingId;
      }

      id = R.id.restaurant;
      Button restaurant = ViewBindings.findChildViewById(rootView, id);
      if (restaurant == null) {
        break missingId;
      }

      id = R.id.roles;
      Button roles = ViewBindings.findChildViewById(rootView, id);
      if (roles == null) {
        break missingId;
      }

      id = R.id.set;
      Button set = ViewBindings.findChildViewById(rootView, id);
      if (set == null) {
        break missingId;
      }

      id = R.id.transport;
      Button transport = ViewBindings.findChildViewById(rootView, id);
      if (transport == null) {
        break missingId;
      }

      id = R.id.users;
      Button users = ViewBindings.findChildViewById(rootView, id);
      if (users == null) {
        break missingId;
      }

      return new HomepageadminBinding((LinearLayout) rootView, airline, attract, covermenuad,
          helpadmin, hotel, messages, openmenuad, out, restaurant, roles, set, transport, users);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
