// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LoginBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText emall;

  @NonNull
  public final Button forgetpass;

  @NonNull
  public final Button loginbtn;

  @NonNull
  public final EditText passl;

  private LoginBinding(@NonNull LinearLayout rootView, @NonNull EditText emall,
      @NonNull Button forgetpass, @NonNull Button loginbtn, @NonNull EditText passl) {
    this.rootView = rootView;
    this.emall = emall;
    this.forgetpass = forgetpass;
    this.loginbtn = loginbtn;
    this.passl = passl;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LoginBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.emall;
      EditText emall = ViewBindings.findChildViewById(rootView, id);
      if (emall == null) {
        break missingId;
      }

      id = R.id.forgetpass;
      Button forgetpass = ViewBindings.findChildViewById(rootView, id);
      if (forgetpass == null) {
        break missingId;
      }

      id = R.id.loginbtn;
      Button loginbtn = ViewBindings.findChildViewById(rootView, id);
      if (loginbtn == null) {
        break missingId;
      }

      id = R.id.passl;
      EditText passl = ViewBindings.findChildViewById(rootView, id);
      if (passl == null) {
        break missingId;
      }

      return new LoginBinding((LinearLayout) rootView, emall, forgetpass, loginbtn, passl);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
