// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class MessagesBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button mesback;

  @NonNull
  public final ListView messagesListView;

  private MessagesBinding(@NonNull LinearLayout rootView, @NonNull Button mesback,
      @NonNull ListView messagesListView) {
    this.rootView = rootView;
    this.mesback = mesback;
    this.messagesListView = messagesListView;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static MessagesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MessagesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.messages, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MessagesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.mesback;
      Button mesback = ViewBindings.findChildViewById(rootView, id);
      if (mesback == null) {
        break missingId;
      }

      id = R.id.messagesListView;
      ListView messagesListView = ViewBindings.findChildViewById(rootView, id);
      if (messagesListView == null) {
        break missingId;
      }

      return new MessagesBinding((LinearLayout) rootView, mesback, messagesListView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
