// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SignupBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final EditText emails;

  @NonNull
  public final EditText passs;

  @NonNull
  public final Button reg;

  @NonNull
  public final EditText uname;

  private SignupBinding(@NonNull LinearLayout rootView, @NonNull EditText emails,
      @NonNull EditText passs, @NonNull Button reg, @NonNull EditText uname) {
    this.rootView = rootView;
    this.emails = emails;
    this.passs = passs;
    this.reg = reg;
    this.uname = uname;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SignupBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SignupBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.signup, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SignupBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.emails;
      EditText emails = ViewBindings.findChildViewById(rootView, id);
      if (emails == null) {
        break missingId;
      }

      id = R.id.passs;
      EditText passs = ViewBindings.findChildViewById(rootView, id);
      if (passs == null) {
        break missingId;
      }

      id = R.id.reg;
      Button reg = ViewBindings.findChildViewById(rootView, id);
      if (reg == null) {
        break missingId;
      }

      id = R.id.uname;
      EditText uname = ViewBindings.findChildViewById(rootView, id);
      if (uname == null) {
        break missingId;
      }

      return new SignupBinding((LinearLayout) rootView, emails, passs, reg, uname);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
