// Generated by view binder compiler. Do not edit!
package com.example.travelcompanion.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.travelcompanion.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class UsersBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button refreshusers;

  @NonNull
  public final Button userback;

  @NonNull
  public final ListView userslist;

  private UsersBinding(@NonNull LinearLayout rootView, @NonNull Button refreshusers,
      @NonNull Button userback, @NonNull ListView userslist) {
    this.rootView = rootView;
    this.refreshusers = refreshusers;
    this.userback = userback;
    this.userslist = userslist;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static UsersBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static UsersBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.users, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static UsersBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.refreshusers;
      Button refreshusers = ViewBindings.findChildViewById(rootView, id);
      if (refreshusers == null) {
        break missingId;
      }

      id = R.id.userback;
      Button userback = ViewBindings.findChildViewById(rootView, id);
      if (userback == null) {
        break missingId;
      }

      id = R.id.userslist;
      ListView userslist = ViewBindings.findChildViewById(rootView, id);
      if (userslist == null) {
        break missingId;
      }

      return new UsersBinding((LinearLayout) rootView, refreshusers, userback, userslist);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
